#### Render Blueprint specification: https://dashboard.render.com/blueprints ####
## 👇 Preview environments: https://render.com/docs/preview-environments ###
# previewsEnabled: true
## 👇 Automatically nuke the environment after X days of inactivity to reduce billing:
# previewsExpireAfterDays: 2
services:
  - type: web
    name: sc-assignment
    env: node
    plan: free
    ## 👇 Specify the plan for the PR deployment:
    # previewPlan: starter
    ## 👇 Preview Environment Initialization script:
    # initialDeployHook: pnpm db-seed
    buildCommand: pnpm install && pnpm build && pnpm migrate && pnpm db-seed
    startCommand: pnpm start
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sc-assignment-db
          property: connectionString

databases:
  - name: sc-assignment-db
    plan: free
